## Matrix

## 행렬의 기본 개념 및 용어

- **행렬(matrix)**: 수나 문자 등을 일정한 모양으로 배열한 것.
- **행(row)**: 행렬의 가로 줄. 
- **열(column)**: 행렬의 세로 줄.
- **m x n 행렬**: m개의 행과 n개의 열로 구성된 행렬. m과 n은 자연수입니다.
- **정사각 행렬(square matrix)**: 행의 개수와 열의 개수가 같은 행렬.
- **대각 행렬(diagonal matrix)**: 주 대각선을 제외한 모든 요소가 0인 정사각 행렬.



In [3]:
import numpy as np

# 행렬 생성
A = np.array([[1, 2], [3, 4], [5, 6]])
print("행렬 A:")
print(A)


행렬 A:
[[1 2]
 [3 4]
 [5 6]]


In [4]:
# 행과 열의 개수
m, n = A.shape
print(f"행렬 A는 {m}x{n} 행렬입니다.")


행렬 A는 3x2 행렬입니다.


In [5]:
# 행 출력
print("행렬 A의 첫 번째 행:")
print(A[0, :])


행렬 A의 첫 번째 행:
[1 2]


In [6]:
# 열 출력
print("행렬 A의 첫 번째 열:")
print(A[:, 0])

행렬 A의 첫 번째 열:
[1 3 5]


In [7]:
# 정사각 행렬
B = np.array([[1, 2], [3, 4]])
print("정사각 행렬 B:")
print(B)


정사각 행렬 B:
[[1 2]
 [3 4]]


In [8]:
# 대각 행렬
C = np.array([[5, 0], [0, 3]])
print("대각 행렬 C:")
print(C)


대각 행렬 C:
[[5 0]
 [0 3]]


## 행렬의 덧셈과 뺄셈

두 행렬 A와 B의 덧셈 또는 뺄셈을 수행하려면 먼저 두 행렬의 크기가 같아야 합니다.

예시:
$$
A = \begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
e & f \\
g & h \\
\end{bmatrix}
$$

$$
A + B = \begin{bmatrix}
a + e & b + f \\
c + g & d + h \\
\end{bmatrix}
$$

$$
A - B = \begin{bmatrix}
a - e & b - f \\
c - g & d - h \\
\end{bmatrix}
$$

In [9]:
# 행렬 A와 B 생성
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("행렬 A:")
print(A)
print()
print("행렬 B:")
print(B)
print()


행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[4 5]
 [6 7]]



In [11]:
# 행렬의 덧셈
C = A + B
print("행렬 A와 B의 덧셈 결과:")
print(C)
print()

# 행렬의 뺄셈
D = A - B
print("행렬 A와 B의 뺄셈 결과:")
print(D)


행렬 A와 B의 덧셈 결과:
[[ 5  7]
 [ 9 11]]

행렬 A와 B의 뺄셈 결과:
[[-3 -3]
 [-3 -3]]


In [12]:
# 크기가 다른 행렬들 생성
E = np.array([[1, 2, 3], [4, 5, 6]])
F = np.array([[7, 8], [9, 10]])

print("행렬 E:")
print(E)
print()
print("행렬 F:")
print(F)
print()

# 크기가 다른 행렬들의 덧셈 시도
try:
    G = E + F
    print("행렬 E와 F의 덧셈 결과:")
    print(G)
except ValueError as e:
    print(f"행렬 E와 F의 덧셈 오류: {e}")

행렬 E:
[[1 2 3]
 [4 5 6]]

행렬 F:
[[ 7  8]
 [ 9 10]]

행렬 E와 F의 덧셈 오류: operands could not be broadcast together with shapes (2,3) (2,2) 


## 스칼라 연산

스칼라(scalar)는 단순한 숫자 값을 의미합니다. 행렬에 스칼라를 곱하는 것은 행렬의 각 요소에 그 스칼라를 곱하는 것과 같습니다.

예시:

$$
k \times \begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
= \begin{bmatrix}
ka & kb \\
kc & kd \\
\end{bmatrix}
$$

In [13]:
# 행렬 A 생성
A = np.array([[1, 2], [3, 4]])
print("행렬 A:")
print(A)
print()

# 스칼라 값 정의
k = 3

# 스칼라와 행렬의 곱
B = k * A
print(f"스칼라 {k}와 행렬 A의 곱 결과:")
print(B)

행렬 A:
[[1 2]
 [3 4]]

스칼라 3와 행렬 A의 곱 결과:
[[ 3  6]
 [ 9 12]]



## 선형사상과 행렬의 곱셈

- **선형사상(linear transformation)**: 벡터 공간의 벡터를 다른 벡터 공간의 벡터로 대응시키는 함수. 선형사상은 덧셈과 스칼라 곱에 대하여 보존하는 특성을 가집니다.

- **행렬의 곱셈**: 두 행렬의 곱셈은 첫 번째 행렬의 행과 두 번째 행렬의 열의 요소들을 순서대로 곱한 후 더하는 방식으로 이루어집니다. 첫 번째 행렬의 열의 수와 두 번째 행렬의 행의 수가 같아야 곱셈이 가능합니다.

예시:

$$
A = \begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
e & f \\
g & h \\
\end{bmatrix}
$$

$$
A \times B = \begin{bmatrix}
a \times e + b \times g & a \times f + b \times h \\
c \times e + d \times g & c \times f + d \times h \\
\end{bmatrix}
$$

In [17]:
# 선형사상 예시
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 행렬
v = np.array([7, 8, 9])               # 3차원 벡터

# 선형사상 결과
w = np.dot(A, v)
print("선형사상 결과 (3D -> 2D):")
print(w)

선형사상 결과 (3D -> 2D):
[ 50 122]


In [15]:

# 행렬의 곱셈 예시
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 행렬
C = np.array([[1, 2, 3], [4, 5, 6]])    # 2x3 행렬

# 행렬의 곱셈 결과
D = np.dot(B, C)
print("행렬 B와 C의 곱셈 결과:")
print(D)


행렬 B와 C의 곱셈 결과:
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
