In [1]:
import numpy as np


a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a)

[1 2 3 4]


## Speed of dot product 

In [2]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

Vectorized version: 5.766391754150391ms


In [4]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print("For loop: " + str(1000*(toc-tic)) + "ms")

For loop: 202.74806022644043ms


## Broadcasting

In [5]:
# Broadcasting

A = np.array([[56.0, 0.0, 4.4, 68.0],
                [1.2, 104.0, 52.0, 8.0],
                [1.8, 135.0, 99.0, 0.9]])

print(A)
print(A.shape)
print(A.T)
print(A.T.shape)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
(3, 4)
[[ 56.    1.2   1.8]
 [  0.  104.  135. ]
 [  4.4  52.   99. ]
 [ 68.    8.    0.9]]
(4, 3)


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
a = np.random.randn(5)

print(a)
print(a.shape)

[ 1.21582408 -0.7419178  -1.67145335 -0.45920772 -0.94535493]
(5,)


In [10]:
# rank 1 array


# transpose
print(a.T)

[ 1.21582408 -0.7419178  -1.67145335 -0.45920772 -0.94535493]


In [11]:
# dot product
print(np.dot(a, a.T))

5.92699419674447


In [12]:
# recommended
a = np.random.randn(5, 1)
print(a)
print(a.T) # two brackets

[[-0.25836573]
 [ 1.2016602 ]
 [-1.02746806]
 [ 0.13228833]
 [-1.99661467]]
[[-0.25836573  1.2016602  -1.02746806  0.13228833 -1.99661467]]


In [13]:
print(np.dot(a, a.T))

[[ 0.06675285 -0.31046781  0.26546253 -0.03417877  0.5158568 ]
 [-0.31046781  1.44398724 -1.23466748  0.15896562 -2.39925239]
 [ 0.26546253 -1.23466748  1.05569062 -0.13592203  2.05145781]
 [-0.03417877  0.15896562 -0.13592203  0.0175002  -0.26412881]
 [ 0.5158568  -2.39925239  2.05145781 -0.26412881  3.98647014]]


In [14]:
# assert(a.shape == (5, 1))
a = a.reshape((5, 1))
print(a.shape)

(5, 1)


In [15]:
a = np.random.randn(12288, 150) # 12288 = 64 * 64 * 3
b = np.random.randn(150, 45)
c = np.dot(a, b)
# print(c.shape)


In [16]:
# losgistict loss?
